// <auto-generated />
using System;
using LetsLearn.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LetsLearn.Infrastructure.Migrations
{
    [DbContext(typeof(LetsLearnContext))]
    [Migration("20261006080800_AddLearningActivityLog")]
    partial class AddLearningActivityLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LetsLearn.Core.Entities.AiEvaluationResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BloomAlignment")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Clarity")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DistractorQuality")
                        .HasColumnType("numeric");

                    b.Property<decimal>("FinalScore")
                        .HasColumnType("numeric");

                    b.Property<Guid>("GeneratedQuestionId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Grounding")
                        .HasColumnType("numeric");

                    b.Property<string>("ReasonsJson")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedQuestionId");

                    b.ToTable("AiEvaluationResults");
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.AiGeneratedQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer");

                    b.Property<string>("BloomLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChoicesJson")
                        .HasColumnType("text");

                    b.Property<string>("CourseId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Feedback")
                        .HasColumnType("text");

                    b.Property<string>("GroundingRefsJson")
                        .HasColumnType("text");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<string>("QuestionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Score")
                        .HasColumnType("numeric");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "Score");

                    b.ToTable("AiGeneratedQuestions");
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.AiQuestionGenerationJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BloomLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CourseId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("KnowledgePoint")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("QuestionCount")
                        .HasColumnType("integer");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RetrievalTopK")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AiQuestionGenerationJobs");
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.AssignmentResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("GradedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GradedBy")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Mark")
                        .HasColumnType("numeric");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("AssignmentResponses");
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.CloudinaryFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignmentResponseId")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayUrl")
                        .HasColumnType("text");

                    b.Property<string>("DownloadUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("TopicAssignmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TopicFileId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TopicFileTopicId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentResponseId");

                    b.HasIndex("TopicAssignmentId");

                    b.HasIndex("TopicFileId")
                        .IsUnique();

                    b.HasIndex("TopicFileTopicId")
                        .IsUnique();

                    b.ToTable("CloudinaryFiles");
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ParentCommentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RootCommentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("RootCommentId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("User1Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("User2Id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.Course", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("Level")
                        .HasColumnType("text");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalJoined")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.Enrollment", b =>
                {
                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<string>("CourseId")
                        .HasColumnType("text");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("StudentId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.LearningActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CourseId")
                        .HasColumnType("text");

                    b.Property<string>("EventSource")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Metadata")
                        .HasColumnType("text");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("TopicId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EventType");

                    b.HasIndex("CourseId", "OccurredAt");

                    b.HasIndex("TopicId", "OccurredAt");

                    b.HasIndex("UserId", "OccurredAt");

                    b.ToTable("LearningActivityLogs");
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.LearningProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CompletedTopicCount")
                        .HasColumnType("integer");

                    b.Property<string>("CourseId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastActivityAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ProgressPercent")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalTopicCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.HasIndex("StudentId", "CourseId")
                        .IsUnique();

                    b.ToTable("LearningProgresses");
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.LectureChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChunkOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CourseId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("EmbeddingJson")
                        .HasColumnType("text");

                    b.Property<string>("EmbeddingModel")
                        .HasColumnType("text");

                    b.Property<string>("Heading")
                        .HasColumnType("text");

                    b.Property<int?>("PageNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId", "ChunkOrder");

                    b.ToTable("LectureChunks");
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.LectureDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CourseId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UploadedById")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("LectureDocuments");
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<string>("FileUrl")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Data")
                        .HasColumnType("text");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("CourseId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("OrderId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TransactionId")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CorrectAnswer")
                        .HasColumnType("boolean");

                    b.Property<string>("CourseId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("DefaultMark")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FeedbackOfFalse")
                        .HasColumnType("text");

                    b.Property<string>("FeedbackOfTrue")
                        .HasColumnType("text");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uuid");

                    b.Property<bool>("Multiple")
                        .HasColumnType("boolean");

                    b.Property<string>("QuestionName")
                        .HasColumnType("text");

                    b.Property<string>("QuestionText")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("Usage")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.QuestionChoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Feedback")
                        .HasColumnType("text");

                    b.Property<decimal?>("GradePercent")
                        .HasColumnType("numeric");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionChoices");
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.QuizResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("QuizResponses");
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.QuizResponseAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Answer")
                        .HasColumnType("text");

                    b.Property<decimal?>("Mark")
                        .HasColumnType("numeric");

                    b.Property<string>("Question")
                        .HasColumnType("text");

                    b.Property<Guid>("QuizResponseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuizResponseId");

                    b.ToTable("QuizResponseAnswers");
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.Section", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CourseId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("Position")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.TopicAssignment", b =>
                {
                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Close")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("MaximumFile")
                        .HasColumnType("integer");

                    b.Property<string>("MaximumFileSize")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Open")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RemindToGrade")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TopicId");

                    b.ToTable("TopicAssignments");
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.TopicFile", b =>
                {
                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.HasKey("TopicId");

                    b.ToTable("TopicFiles");
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.TopicLink", b =>
                {
                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("TopicId");

                    b.ToTable("TopicLinks");
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.TopicMeeting", b =>
                {
                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Close")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("MeetingLink")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Open")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TopicId");

                    b.ToTable("TopicMeetings");
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.TopicMeetingHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AttendanceCsvUrl")
                        .HasColumnType("text");

                    b.Property<int>("AttendeeCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TopicMeetingId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TopicMeetingId");

                    b.ToTable("TopicMeetingHistories");
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.TopicPage", b =>
                {
                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.HasKey("TopicId");

                    b.ToTable("TopicPages");
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.TopicProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CompletionSource")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CourseId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FirstAccessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastAccessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.HasIndex("CourseId", "StudentId");

                    b.HasIndex("StudentId", "TopicId")
                        .IsUnique();

                    b.ToTable("TopicProgresses");
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.TopicQuiz", b =>
                {
                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid");

                    b.Property<string>("AttemptAllowed")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Close")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal?>("GradeToPass")
                        .HasColumnType("numeric");

                    b.Property<string>("GradingMethod")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Open")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TimeLimit")
                        .HasColumnType("integer");

                    b.Property<string>("TimeLimitUnit")
                        .HasColumnType("text");

                    b.HasKey("TopicId");

                    b.ToTable("TopicQuizzes");
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.TopicQuizQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool?>("CorrectAnswer")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("DefaultMark")
                        .HasColumnType("numeric");

                    b.Property<string>("FeedbackOfFalse")
                        .HasColumnType("text");

                    b.Property<string>("FeedbackOfTrue")
                        .HasColumnType("text");

                    b.Property<bool?>("Multiple")
                        .HasColumnType("boolean");

                    b.Property<string>("QuestionName")
                        .HasColumnType("text");

                    b.Property<string>("QuestionText")
                        .HasColumnType("text");

                    b.Property<Guid>("TopicQuizId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TopicQuizId");

                    b.ToTable("TopicQuizQuestions");
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.TopicQuizQuestionChoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Feedback")
                        .HasColumnType("text");

                    b.Property<decimal?>("GradePercent")
                        .HasColumnType("numeric");

                    b.Property<Guid>("QuizQuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("QuizQuestionId");

                    b.ToTable("TopicQuizQuestionChoices");
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.AiEvaluationResult", b =>
                {
                    b.HasOne("LetsLearn.Core.Entities.AiGeneratedQuestion", null)
                        .WithMany()
                        .HasForeignKey("GeneratedQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.AiGeneratedQuestion", b =>
                {
                    b.HasOne("LetsLearn.Core.Entities.AiQuestionGenerationJob", null)
                        .WithMany("Questions")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.CloudinaryFile", b =>
                {
                    b.HasOne("LetsLearn.Core.Entities.AssignmentResponse", null)
                        .WithMany("Files")
                        .HasForeignKey("AssignmentResponseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LetsLearn.Core.Entities.TopicAssignment", null)
                        .WithMany("Files")
                        .HasForeignKey("TopicAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LetsLearn.Core.Entities.TopicFile", null)
                        .WithOne()
                        .HasForeignKey("LetsLearn.Core.Entities.CloudinaryFile", "TopicFileId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LetsLearn.Core.Entities.TopicFile", null)
                        .WithOne("File")
                        .HasForeignKey("LetsLearn.Core.Entities.CloudinaryFile", "TopicFileTopicId");
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.Comment", b =>
                {
                    b.HasOne("LetsLearn.Core.Entities.Comment", null)
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LetsLearn.Core.Entities.Comment", null)
                        .WithMany()
                        .HasForeignKey("RootCommentId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.Enrollment", b =>
                {
                    b.HasOne("LetsLearn.Core.Entities.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LetsLearn.Core.Entities.User", null)
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.LearningActivityLog", b =>
                {
                    b.HasOne("LetsLearn.Core.Entities.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LetsLearn.Core.Entities.Topic", null)
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LetsLearn.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.LearningProgress", b =>
                {
                    b.HasOne("LetsLearn.Core.Entities.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LetsLearn.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.LectureChunk", b =>
                {
                    b.HasOne("LetsLearn.Core.Entities.LectureDocument", null)
                        .WithMany("Chunks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.Message", b =>
                {
                    b.HasOne("LetsLearn.Core.Entities.Conversation", null)
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.QuestionChoice", b =>
                {
                    b.HasOne("LetsLearn.Core.Entities.Question", null)
                        .WithMany("Choices")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.QuizResponseAnswer", b =>
                {
                    b.HasOne("LetsLearn.Core.Entities.QuizResponse", null)
                        .WithMany("Answers")
                        .HasForeignKey("QuizResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.RefreshToken", b =>
                {
                    b.HasOne("LetsLearn.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.Section", b =>
                {
                    b.HasOne("LetsLearn.Core.Entities.Course", null)
                        .WithMany("Sections")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.Topic", b =>
                {
                    b.HasOne("LetsLearn.Core.Entities.Section", null)
                        .WithMany("Topics")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.TopicAssignment", b =>
                {
                    b.HasOne("LetsLearn.Core.Entities.Topic", null)
                        .WithOne()
                        .HasForeignKey("LetsLearn.Core.Entities.TopicAssignment", "TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.TopicFile", b =>
                {
                    b.HasOne("LetsLearn.Core.Entities.Topic", null)
                        .WithOne()
                        .HasForeignKey("LetsLearn.Core.Entities.TopicFile", "TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.TopicLink", b =>
                {
                    b.HasOne("LetsLearn.Core.Entities.Topic", null)
                        .WithOne()
                        .HasForeignKey("LetsLearn.Core.Entities.TopicLink", "TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.TopicMeeting", b =>
                {
                    b.HasOne("LetsLearn.Core.Entities.Topic", null)
                        .WithOne()
                        .HasForeignKey("LetsLearn.Core.Entities.TopicMeeting", "TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.TopicMeetingHistory", b =>
                {
                    b.HasOne("LetsLearn.Core.Entities.TopicMeeting", null)
                        .WithMany("Histories")
                        .HasForeignKey("TopicMeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.TopicPage", b =>
                {
                    b.HasOne("LetsLearn.Core.Entities.Topic", null)
                        .WithOne()
                        .HasForeignKey("LetsLearn.Core.Entities.TopicPage", "TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.TopicProgress", b =>
                {
                    b.HasOne("LetsLearn.Core.Entities.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LetsLearn.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LetsLearn.Core.Entities.Topic", null)
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.TopicQuiz", b =>
                {
                    b.HasOne("LetsLearn.Core.Entities.Topic", null)
                        .WithOne()
                        .HasForeignKey("LetsLearn.Core.Entities.TopicQuiz", "TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.TopicQuizQuestion", b =>
                {
                    b.HasOne("LetsLearn.Core.Entities.TopicQuiz", null)
                        .WithMany("Questions")
                        .HasForeignKey("TopicQuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.TopicQuizQuestionChoice", b =>
                {
                    b.HasOne("LetsLearn.Core.Entities.TopicQuizQuestion", null)
                        .WithMany("Choices")
                        .HasForeignKey("QuizQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.AiQuestionGenerationJob", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.AssignmentResponse", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.Comment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.Course", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.LectureDocument", b =>
                {
                    b.Navigation("Chunks");
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.Question", b =>
                {
                    b.Navigation("Choices");
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.QuizResponse", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.Section", b =>
                {
                    b.Navigation("Topics");
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.TopicAssignment", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.TopicFile", b =>
                {
                    b.Navigation("File");
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.TopicMeeting", b =>
                {
                    b.Navigation("Histories");
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.TopicQuiz", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.TopicQuizQuestion", b =>
                {
                    b.Navigation("Choices");
                });

            modelBuilder.Entity("LetsLearn.Core.Entities.User", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
